### ISSUE TITLE
[1.2.1] Will breaks the VisualEditor

### ISSUE THREAD

**Issue by tuxmaster5000** [thaider/Tweeki#194] opened 2021-05-03 07:42 UTC
When the tweeki skin is loaded, then the VisualEditor on MW 1.35.2 fails to load with:
VisualEditor failed to load: Error: One or more dependencies failed to load

**Comment by thaider** [comment] 2021-05-27 19:10
Duplicate of #180

**Closed by thaider** 2021-05-27 19:10 UTC
