### ISSUE TITLE
Strange bug with a single dot

### ISSUE THREAD

**Issue by chdioux** [thaider/Tweeki#146] opened 2019-05-16 10:39 UTC
Hello,
I'm not a dev, just a simple end-user, but i really love Tweeki and hope i can help a little with the following bug report.

With this wiki code:

==line 1.==
===line 2===
* [[link 1]]
* [[link 2]]
* [[link 3]]
* [[link 4]]

==line 7==
===line 8===

Links 3 and 4 don't work any more (at least under Firefox 66.0.5 for Ubuntu). If I swap to vector skin, they do work properly again. And if i delete the point at the end of line 1, everything works fine again. If i delete lines 7 and 8, everything works again too.

It's not a big problem, as it is solved by the removal of the point, but i found this amazing. Hope this small bug report might help. My apologies if not. And thanks again for Tweeki!

**Comment by thaider** [comment] 2019-05-17 09:06
Thanks for reporting!

This has the same cause as #140 – the dot results in a javascript error and prevents the execution of other essential code. Should be fixed in the latest version of Tweeki. Could you please update, test, and confirm?

Duplicate of 140#

**Comment by chdioux** [comment] 2019-05-17 09:52
Thanks! I confirm: Bug is fixed with the latest version. Have a good day.

**Comment by chdioux** [comment] 2019-05-22 08:55
Hi Thaider!
Sorry to reopen this issue, but if the latest version did fix the dot/javascript problem, it came at a cost, at least on my system:
Previews (while editing) didn't work anymore! And this, with all skins, even Vector.
Back to the old Teeki version, previews work fine again.

**Closed** 2019-05-22 14:28 UTC

**Comment by thaider** [comment] 2019-05-22 14:31
Thanks for the report. The issue was indeed a related side effect and should be fixed in the latest code...
